### ISSUE TITLE
pbs-ruby configuration is incorrect for oakley and ruby

### ISSUE THREAD

**Issue by ericfranz** [OSC/pbs-ruby#14]
I cannot submit jobs to Oakley or Ruby from osc-machete, which depends on the default configuration file in pbs-ruby for OSC.

The reason is here https://github.com/AweSim-OSC/pbs-ruby/blob/304a716e6785f141bb8beb28b1974e5ef481faf3/config/batch.yml#L7-L16

``` yaml
oakley: &oakley
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: &oakley_server 'oak-batch.osc.edu'
    qsub: 'LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH /usr/local/torque-4.2.8/bin/qsub'
*oakley_server:
  <<: *oakley
ruby: &ruby
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: &ruby_server 'ruby-batch.ten.osc.edu'
    qsub: 'LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH /usr/local/torque-4.2.8/bin/qsub'
```
1. The path to qsub for Oakley is actually `/usr/local/torque/4.2.8/bin/qsub` not `/usr/local/torque-4.2.8/bin/qsub` which doesn't exist.
2. The default torque version used on the login node is higher: 
   
   ```
   efranz@oakley02:~/awesim_dev/rails1 (port)$ which qsub
   /usr/local/torque/5.1.2-1448394813_f498aba/bin/qsub
   ```
3. 4.2.8 doesn't even exist on Ruby, and the default is also 5.1.2
   
   ```
   efranz@ruby01:~$ ls /usr/local/torque -1
   .
   ..
   2.5.10
   2.5.10-no-cpusets
   2.5.10-nvml
   2.5.10-nvml2
   2.5.10-svn
   2.5.12
   2.5.12-fix_mom_priv
   2.5.12-hugemem
   2.5.12-mem-cgroup
   2.5.8
   2.5.9
   4.0.0-20120125
   4.2.6
   4.2.7
   5.0.0
   5.0.1
   5.1.0
   5.1.1-1_fba25d92
   5.1.2-1448394813_f498aba
   default
   efranz@ruby01:~$ which qsub
   /usr/local/torque/5.1.2-1448394813_f498aba/bin/qsub
   efranz@ruby01:~$
   ```

The result is I cannot submit jobs from Oakley or Ruby using our libraries.

Note that we should probably provide a method through osc-machete & osc_machete_rails via a custom TorqueAdapter to change the configuration file. The osc-machete issue https://github.com/AweSim-OSC/osc-machete/issues/96 addresses this code change.
